version: '3'
services:
  influxdb:
    image: "influxdb"
    ports: 
     - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
      - $PWD/influxdb.conf:/etc/influxdb/influxdb.conf
        
   telegraf: 
     image: "telegraf"

   grafana:
     image: "grafana"
     ports:
      - "3000:3000"
 

