version: '3'
services:
  influxdb:
    image: "influxdb"
    ports:
     - "8086:8086"
     - "8083:8083" 
    volumes:
      - influxdb:/var/lib/influxdb
      - $PWD/influxdb.conf:/etc/influxdb/influxdb.conf
    environment: 
      - INFLUXDB_ADMIN_USER=telegraf
      - INFLUXDB_ADMIN_PASSWORD=telegraf
#     - INFLUXDB_USER=testuser
#     - INFLUXDB_USER_PASSWORD=supersecret
 
  telegraf:
    image: "telegraf"


  grafana:
    image: "docker.io/grafana/grafana"
    ports:
      - "3000:3000"

volumes:
  influxdb:
